import { Injectable } from '@angular/core';

import { Resort } from '../interfaces/resort';

@Injectable({
  providedIn: 'root'
})
export class ResortsService {
  resorts: Resort[] = [
    {
      image: 'resort1',
      spa: true,
      wifi: true,
      abc: true,
      p: true,
      food: true,
      best: true,
      discount: true,
      pool: false,
      thermal: false,
      spaH: false,
      title: 'Міротель',
      subtitle: 'Новий готельний комплекс Міротель (Mirotel)​ Трускавець відкрив свої двері в 2012 році ',
      priceNow: 'від 2610 грн',
      priceLast: '',
      green: false,
      people: 1
    },
    {
      image: 'resort2',
      spa: true,
      wifi: true,
      abc: false,
      p: false,
      food: false,
      best: false,
      discount: false,
      pool: true,
      thermal: false,
      spaH: false,
      title: 'Санаторій Алмаз Трускавець ',
      subtitle: 'Новий готельний комплекс Міротель (Mirotel)​ Трускавець відкрив свої двері в 2012 році ',
      priceNow: '680 грн',
      priceLast: 'від 800 грн',
      green: true,
      people: 1
    },
    {
      image: 'resort3',
      spa: true,
      wifi: true,
      abc: false,
      p: true,
      food: true,
      best: false,
      discount: false,
      pool: false,
      thermal: true,
      spaH: false,
      title: 'Вілла Гранд (Villa Grand) Східниця',
      subtitle: 'Новий готельний комплекс Міротель (Mirotel)​ Трускавець відкрив свої двері в 2012 році ',
      priceNow: 'від 2610 грн',
      priceLast: '',
      green: false,
      people: 1
    },
    {
      image: 'resort2',
      spa: false,
      wifi: true,
      abc: true,
      p: true,
      food: true,
      best: false,
      discount: false,
      pool: false,
      thermal: false,
      spaH: true,
      title: 'Санаторій Алмаз Трускавець',
      subtitle: 'Новий готельний комплекс Міротель (Mirotel)​ Трускавець відкрив свої двері в 2012 році ',
      priceNow: 'від 800 грн',
      priceLast: '',
      green: false,
      people: 2
    },
    {
      image: 'resort1',
      spa: true,
      wifi: true,
      abc: true,
      p: true,
      food: true,
      best: true,
      discount: true,
      pool: false,
      thermal: false,
      spaH: false,
      title: 'Міротель',
      subtitle: 'Новий готельний комплекс Міротель (Mirotel)​ Трускавець відкрив свої двері в 2012 році ',
      priceNow: 'від 2610 грн',
      priceLast: '',
      green: false,
      people: 1
    },
    {
      image: 'resort2',
      spa: true,
      wifi: true,
      abc: false,
      p: false,
      food: false,
      best: false,
      discount: false,
      pool: true,
      thermal: false,
      spaH: false,
      title: 'Санаторій Алмаз Трускавець ',
      subtitle: 'Новий готельний комплекс Міротель (Mirotel)​ Трускавець відкрив свої двері в 2012 році ',
      priceNow: '680 грн',
      priceLast: 'від 800 грн',
      green: true,
      people: 1
    },
    {
      image: 'resort3',
      spa: true,
      wifi: true,
      abc: false,
      p: true,
      food: true,
      best: false,
      discount: false,
      pool: false,
      thermal: true,
      spaH: false,
      title: 'Вілла Гранд (Villa Grand) Східниця',
      subtitle: 'Новий готельний комплекс Міротель (Mirotel)​ Трускавець відкрив свої двері в 2012 році ',
      priceNow: 'від 2610 грн',
      priceLast: '',
      green: false,
      people: 1
    },
    {
      image: 'resort2',
      spa: false,
      wifi: true,
      abc: true,
      p: true,
      food: true,
      best: false,
      discount: false,
      pool: false,
      thermal: false,
      spaH: true,
      title: 'Санаторій Алмаз Трускавець',
      subtitle: 'Новий готельний комплекс Міротель (Mirotel)​ Трускавець відкрив свої двері в 2012 році ',
      priceNow: 'від 800 грн',
      priceLast: '',
      green: false,
      people: 2
    },
    {
      image: 'resort1',
      spa: true,
      wifi: true,
      abc: true,
      p: true,
      food: true,
      best: true,
      discount: true,
      pool: false,
      thermal: false,
      spaH: false,
      title: 'Міротель',
      subtitle: 'Новий готельний комплекс Міротель (Mirotel)​ Трускавець відкрив свої двері в 2012 році ',
      priceNow: 'від 2610 грн',
      priceLast: '',
      green: false,
      people: 1
    },
    {
      image: 'resort2',
      spa: true,
      wifi: true,
      abc: false,
      p: false,
      food: false,
      best: false,
      discount: false,
      pool: true,
      thermal: false,
      spaH: false,
      title: 'Санаторій Алмаз Трускавець ',
      subtitle: 'Новий готельний комплекс Міротель (Mirotel)​ Трускавець відкрив свої двері в 2012 році ',
      priceNow: '680 грн',
      priceLast: 'від 800 грн',
      green: true,
      people: 1
    },
    {
      image: 'resort3',
      spa: true,
      wifi: true,
      abc: false,
      p: true,
      food: true,
      best: false,
      discount: false,
      pool: false,
      thermal: true,
      spaH: false,
      title: 'Вілла Гранд (Villa Grand) Східниця',
      subtitle: 'Новий готельний комплекс Міротель (Mirotel)​ Трускавець відкрив свої двері в 2012 році ',
      priceNow: 'від 2610 грн',
      priceLast: '',
      green: false,
      people: 1
    },
    {
      image: 'resort2',
      spa: false,
      wifi: true,
      abc: true,
      p: true,
      food: true,
      best: false,
      discount: false,
      pool: false,
      thermal: false,
      spaH: true,
      title: 'Санаторій Алмаз Трускавець',
      subtitle: 'Новий готельний комплекс Міротель (Mirotel)​ Трускавець відкрив свої двері в 2012 році ',
      priceNow: 'від 800 грн',
      priceLast: '',
      green: false,
      people: 2
    }
  ]
}
